################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Src/eez \
Core/Src/lvgl/core \
Core/Src/lvgl/debugging/monkey \
Core/Src/lvgl/debugging/sysmon \
Core/Src/lvgl/debugging/test \
Core/Src/lvgl/debugging/vg_lite_tvg \
Core/Src/lvgl/display \
Core/Src/lvgl/draw/convert/helium \
Core/Src/lvgl/draw/convert \
Core/Src/lvgl/draw/convert/neon \
Core/Src/lvgl/draw/dma2d \
Core/Src/lvgl/draw/espressif/ppa \
Core/Src/lvgl/draw/eve \
Core/Src/lvgl/draw \
Core/Src/lvgl/draw/nanovg \
Core/Src/lvgl/draw/nema_gfx \
Core/Src/lvgl/draw/nxp/g2d \
Core/Src/lvgl/draw/nxp/pxp \
Core/Src/lvgl/draw/opengles \
Core/Src/lvgl/draw/renesas/dave2d \
Core/Src/lvgl/draw/sdl \
Core/Src/lvgl/draw/snapshot \
Core/Src/lvgl/draw/sw/blend/helium \
Core/Src/lvgl/draw/sw/blend \
Core/Src/lvgl/draw/sw/blend/neon \
Core/Src/lvgl/draw/sw/blend/riscv_v \
Core/Src/lvgl/draw/sw \
Core/Src/lvgl/draw/vg_lite \
Core/Src/lvgl/drivers/display/drm \
Core/Src/lvgl/drivers/display/fb \
Core/Src/lvgl/drivers/display/ft81x \
Core/Src/lvgl/drivers/display/ili9341 \
Core/Src/lvgl/drivers/display/lcd \
Core/Src/lvgl/drivers/display/nv3007 \
Core/Src/lvgl/drivers/display/nxp_elcdif \
Core/Src/lvgl/drivers/display/renesas_glcdc \
Core/Src/lvgl/drivers/display/st7735 \
Core/Src/lvgl/drivers/display/st7789 \
Core/Src/lvgl/drivers/display/st7796 \
Core/Src/lvgl/drivers/display/st_ltdc \
Core/Src/lvgl/drivers/draw/eve \
Core/Src/lvgl/drivers/evdev \
Core/Src/lvgl/drivers/libinput \
Core/Src/lvgl/drivers/nuttx \
Core/Src/lvgl/drivers/opengles/assets \
Core/Src/lvgl/drivers/opengles/glad/src \
Core/Src/lvgl/drivers/opengles \
Core/Src/lvgl/drivers/opengles/opengl_shader \
Core/Src/lvgl/drivers/qnx \
Core/Src/lvgl/drivers/sdl \
Core/Src/lvgl/drivers/uefi \
Core/Src/lvgl/drivers/wayland \
Core/Src/lvgl/drivers/windows \
Core/Src/lvgl/drivers/x11 \
Core/Src/lvgl/font/binfont_loader \
Core/Src/lvgl/font/fmt_txt \
Core/Src/lvgl/font/font_manager \
Core/Src/lvgl/font/imgfont \
Core/Src/lvgl/font \
Core/Src/lvgl/indev \
Core/Src/lvgl/layouts/flex \
Core/Src/lvgl/layouts/grid \
Core/Src/lvgl/layouts \
Core/Src/lvgl/libs/FT800-FT813 \
Core/Src/lvgl/libs/barcode \
Core/Src/lvgl/libs/bin_decoder \
Core/Src/lvgl/libs/bmp \
Core/Src/lvgl/libs/ffmpeg \
Core/Src/lvgl/libs/freetype \
Core/Src/lvgl/libs/frogfs/src \
Core/Src/lvgl/libs/fsdrv \
Core/Src/lvgl/libs/gif \
Core/Src/lvgl/libs/gltf/gltf_environment \
Core/Src/lvgl/libs/gltf/gltf_view/assets \
Core/Src/lvgl/libs/gltf/math \
Core/Src/lvgl/libs/gstreamer \
Core/Src/lvgl/libs/libjpeg_turbo \
Core/Src/lvgl/libs/libpng \
Core/Src/lvgl/libs/libwebp \
Core/Src/lvgl/libs/lodepng \
Core/Src/lvgl/libs/lz4 \
Core/Src/lvgl/libs/nanovg \
Core/Src/lvgl/libs/qrcode \
Core/Src/lvgl/libs/rle \
Core/Src/lvgl/libs/rlottie \
Core/Src/lvgl/libs/svg \
Core/Src/lvgl/libs/tiny_ttf \
Core/Src/lvgl/libs/tjpgd \
Core/Src/lvgl/libs/vg_lite_driver/VGLite \
Core/Src/lvgl/libs/vg_lite_driver/VGLiteKernel \
Core/Src/lvgl/libs/vg_lite_driver/lv_vg_lite_hal \
Core/Src/lvgl \
Core/Src/lvgl/misc/cache/class \
Core/Src/lvgl/misc/cache/instance \
Core/Src/lvgl/misc/cache \
Core/Src/lvgl/misc \
Core/Src/lvgl/osal \
Core/Src/lvgl/others/file_explorer \
Core/Src/lvgl/others/fragment \
Core/Src/lvgl/others/translation \
Core/Src/lvgl/stdlib/builtin \
Core/Src/lvgl/stdlib/clib \
Core/Src/lvgl/stdlib \
Core/Src/lvgl/stdlib/micropython \
Core/Src/lvgl/stdlib/rtthread \
Core/Src/lvgl/stdlib/uefi \
Core/Src/lvgl/themes/default \
Core/Src/lvgl/themes \
Core/Src/lvgl/themes/mono \
Core/Src/lvgl/themes/simple \
Core/Src/lvgl/tick \
Core/Src/lvgl/widgets/3dtexture \
Core/Src/lvgl/widgets/animimage \
Core/Src/lvgl/widgets/arc \
Core/Src/lvgl/widgets/arclabel \
Core/Src/lvgl/widgets/bar \
Core/Src/lvgl/widgets/button \
Core/Src/lvgl/widgets/buttonmatrix \
Core/Src/lvgl/widgets/calendar \
Core/Src/lvgl/widgets/canvas \
Core/Src/lvgl/widgets/chart \
Core/Src/lvgl/widgets/checkbox \
Core/Src/lvgl/widgets/dropdown \
Core/Src/lvgl/widgets/gif \
Core/Src/lvgl/widgets/image \
Core/Src/lvgl/widgets/imagebutton \
Core/Src/lvgl/widgets/ime \
Core/Src/lvgl/widgets/keyboard \
Core/Src/lvgl/widgets/label \
Core/Src/lvgl/widgets/led \
Core/Src/lvgl/widgets/line \
Core/Src/lvgl/widgets/list \
Core/Src/lvgl/widgets/lottie \
Core/Src/lvgl/widgets/menu \
Core/Src/lvgl/widgets/msgbox \
Core/Src/lvgl/widgets/objx_templ \
Core/Src/lvgl/widgets/property \
Core/Src/lvgl/widgets/roller \
Core/Src/lvgl/widgets/scale \
Core/Src/lvgl/widgets/slider \
Core/Src/lvgl/widgets/span \
Core/Src/lvgl/widgets/spinbox \
Core/Src/lvgl/widgets/spinner \
Core/Src/lvgl/widgets/switch \
Core/Src/lvgl/widgets/table \
Core/Src/lvgl/widgets/tabview \
Core/Src/lvgl/widgets/textarea \
Core/Src/lvgl/widgets/tileview \
Core/Src/lvgl/widgets/win \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src \
Middlewares/ST/STM32_USB_Host_Library/Core/Src \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
USB_HOST/App \
USB_HOST/Target \

